//
//  Localization.swift
//  DnDclassic
//
//  Created by Adam Lovastyik on 26/04/2020.
//  Copyright © 2020 Adam Lovastyik. All rights reserved.
//

import Foundation

struct Localization {
    
    static let buttonTitleOk                    = NSLocalizedString("OK", comment: "OK button title")
    static let buttonTitleCancel                = NSLocalizedString("Cancel", comment: "Cancel option title")
    static let buttontitleBuy                   = NSLocalizedString("Buy", comment: "Buy option title")
    
    static let navigationTitleTrade             = NSLocalizedString("Trade", comment: "Trade scene navigation title")
    static let messageNotEnoghMoney             = NSLocalizedString("You don't have enough money to buy this item", comment: "Message when user does not have enough money to buy an item")
    static let messageAlreadyPurchased          = NSLocalizedString("You already have one of this item", comment: "Message when user already purchased a unique item")
    static let titlePurchase                    = NSLocalizedString("Purchase", comment: "Purchase dialog title")
    static let messageFormatPurchase            = NSLocalizedString("Do you want to buy this item:\n%@\n?", comment: "Purchase dialog message format")
    static let gold                             = NSLocalizedString("gold", comment: "Price label in gold")
    
    static let messageFightOver                 = NSLocalizedString("The battle is over", comment: "Alert message when fight is over")
    static let buttonTitleDrinkPotion           = NSLocalizedString("Drink potion", comment: "Drink potion button title")
    static let titleUseLuck                     = NSLocalizedString("use when hit", comment: "Use luck when hittng on opponent label title")
    static let messageFightWrongOrder           = NSLocalizedString("You have to fight your opponents in sequential order!", comment: "Error message when user wants to find an opponent outside of order")
    static let titlePlayerWonFight              = NSLocalizedString("You won again!", comment: "Alert message when opponent was beaten")
    static let messagePlayerWonFight            = NSLocalizedString("Congratlations!", comment:"Alert title when opponent was beaten")
    
    static let displayFormatProperty            = NSLocalizedString("%d of %d - %0.0f%%", comment: "Character property display format")
    static let health                           = NSLocalizedString("Health", comment: "Heatlh title")
    static let dexterity                        = NSLocalizedString("Dexterity", comment: "Dexterity title")
    static let luck                             = NSLocalizedString("Luck", comment: "Luck title")
    
    static let messageEscapeUnavailable         = NSLocalizedString("You can't escape just yet!", comment: "Alert message when escapeing from fight s not available")
    static let titleDamageSuffered              = NSLocalizedString("You suffered a bad damage from your opponent!", comment: "Alert title when player damage event triggered")
    static let titleDamageMade                  = NSLocalizedString("You made a damage to your opponent!", comment: "Alert title when opponent damage event triggered")
    static let alertMessageAdvance              = NSLocalizedString("You're being taken to %@", comment: "Alert title when damage event triggered")
    static let titleEscape                      = NSLocalizedString("Escape", comment: "Escape title")
    static let messageEscape                    = NSLocalizedString("Are you sure you want to escape? It'll cost you 2 healt points!", comment: "Escape alert message")
    static let titleTryLuck                     = NSLocalizedString("Try your luck", comment: "Try luck title")
    
    static let name                             = NSLocalizedString("Name", comment: "Name title")
    static let properties                       = NSLocalizedString("Properties", comment: "Properties title")
    static let inventory                        = NSLocalizedString("Inventory", comment: "Inventory title")
    static let titleEat                         = NSLocalizedString("Eat", comment: "Eat title")
    static let messageEat                       = NSLocalizedString("Would you like to eat?\nIt increases your health by 4 points and takes one portion of your food rations", comment: "Eat alert sheet message")

    static let messageFormatDexterityPotion     = NSLocalizedString("Restores your dexerity to start level (%d)", comment: "Dexerity potion option alert message format")
    static let messageFormatHealthPotion        = NSLocalizedString("Restores your health to start level (%d)", comment: "Health potion alert message format")
    static let messageFormatLuckPotion          = NSLocalizedString("Restores your luck to start level (%d) and increses starting levelby one", comment: "Luck potoion alert message format")
    static let messageFormatDrinkPotion         = NSLocalizedString("Drink potion of %@?", comment: "Drink potion alert title format")
    static let messageCannotUnequip             = NSLocalizedString("You can not remove this item", comment: "Alert message when cannot unequip inventory item")
    static let messageCannotEquip               = NSLocalizedString("You can not equip this item", comment: "Error message when failed to equip inventory item")
    static let messageFormatInventoryItem       = NSLocalizedString("What would you like to do with %@?", comment: "Inventory item manipulation dialog message format")
    static let buttonTitleUnequip               = NSLocalizedString("Back to inventory", comment: "Un-equip option title")
    static let buttonTitleEquip                 = NSLocalizedString("Equip", comment: "Equip option title")
    static let titleDropItem                    = NSLocalizedString("Drop item", comment: "Drop inventory item option title")
    static let equipped                         = NSLocalizedString("Equipped", comment: "Title when inventory item equipped")

    static let navigationTitleCharacterEdit     = NSLocalizedString("Your character", comment: "Character edit screeen navigation title")
    static let potion                           = NSLocalizedString("Potion", comment: "Potion title")
    static let messageSelectPotion              = NSLocalizedString("Select potion to help you in your journey", comment: "Potion selection dialog message")
    static let titlePotionHealth                = NSLocalizedString("Potion of Health", comment: "Potion of Health title")
    static let titlePotionDexterity             = NSLocalizedString("Potion of Dexterity", comment: "Potion of Dexterity title")
    static let titlePotionLuck                  = NSLocalizedString("Potion of Luck", comment: "Potion of Luck title")
    static let buttontTitleRemove               = NSLocalizedString("Remove", comment: "Remove title")
    
    static let messageNameNotSet                = NSLocalizedString("Please provide name for your character!", comment: "Error message when character name is empty")
    static let messageDexterityNotSet           = NSLocalizedString("Please set dexterty for your character!", comment: "Error message when character dexterity is not set")
    static let messageHealthNotSet              = NSLocalizedString("Please set health for your character!", comment: "Error message when character health is not set")
    static let messageLuckNotset                = NSLocalizedString("Please set luck for your character!", comment: "Error message when character luck is not set")
    static let messageCharacterIncomplete       = NSLocalizedString("Your character is not complete!", comment: "Error dialog title when character properties not set")
    
    static let roll                             = NSLocalizedString("Roll", comment: "Roll button title")
    static let buttonTitleAdd                   = NSLocalizedString("Add", comment: "Add button title")
    static let buttonTitleChange                = NSLocalizedString("Change", comment: "Change button title")
    
    static let navigationTitleFormatScene       = NSLocalizedString("Scene %d", comment: "Scene navigation title format")
    static let goBack                           = NSLocalizedString("Go back", comment: "Go back waypoint title")
    static let restartGame                      = NSLocalizedString("Restart game", comment: "Restart game title when game finished")
    static let messageWaypointNotSelectable     = NSLocalizedString("Sorry, you don't fulfil the condition to choose this way!", comment: "Message when waypoint condition is not fulfilled")
    
    static let messageFormatRoll                = NSLocalizedString("You rolled %d, %@", comment: "Try luck action result message format")
    static let goodLuck                         = NSLocalizedString("Good luck!", comment: "Good luck result title")
    static let badLuck                          = NSLocalizedString("Bad luck :(", comment: "Bad luck result title")
    static let messageFormatGainedGold          = NSLocalizedString("Good luck, you just gained %d gold!", comment: "Good luck dialog message when money is earned")
    static let messageFormatLostGold            = NSLocalizedString("Oh no, you just lost %d gold!", comment: "Bad luck dialog message when money is lost")
    static let titleTriedLuck                   = NSLocalizedString("You tried your luck", comment: "Try luck action result title")
    static let buttonTitleRolAgain              = NSLocalizedString("Roll again", comment: "Roll again option title")
    static let placeholderQueryAnswer           = NSLocalizedString("Enter your answer", comment: "Placeholder for query action textfield title")
    static let titleFinished                    = NSLocalizedString("Finished", comment: "Alert title when game finished")
    static let messageGameFinished              = NSLocalizedString("Your journey has come to an end.", comment: "Alert message when game finished")
    static let buttonTitleRestartSameChar       = NSLocalizedString("Restart with the same character", comment: "Option title to restart game with the same character")
    static let buttonTitleRestartNewChar        = NSLocalizedString("Restart with new character", comment: "Option title to restart game with new character")
    
    static let titleBetGamble                   = NSLocalizedString("How much do you bet?", comment: "Alert title to request bet")
    static let titleGambleWon                   = NSLocalizedString("You won!", comment: "Alert title when player won gambling")
    static let titleGableLost                   = NSLocalizedString("You lost", comment: "Alert title when player lost gambling")
    static let placeholderBet                   = NSLocalizedString("Place your bet", comment: "Bet query placeholder")
    static let titleGamble                      = NSLocalizedString("Gamble", comment: "Title gamble")
    static let messageFormatGableRoll           = NSLocalizedString("You rolled %d, they rolled %d", comment: "Alert message format when rolled in gambling")
    static let messageFormatGambleWin           = NSLocalizedString("You won %d gold", comment: "Alert message format when user won gambling")
    static let messageFormatGambleLost          = NSLocalizedString("You lost %d gold", comment: "Alert message format when user lost gambling")
    static let buttonTitleAnotherRound          = NSLocalizedString("Another round", comment: "Alert option title to gamble another round")
    static let messagePlayerDied                = NSLocalizedString("You just died :(", comment: "Alert message when user gone KIA")
    static let sorry                            = NSLocalizedString("Sorry", comment: "Sorry")
    static let titleResting                     = NSLocalizedString("Resting", comment: "Resting alert title")
    static let messageResting                   = NSLocalizedString("You feel refreshed after resting. Where would you like to go from here?", comment: "Resting alert message")
    
    static let sectionTitleStock                = NSLocalizedString("Items in stock", comment: "Trade section title")
    static let sectionTitleInventory            = NSLocalizedString("Your inventory", comment: "Inventory section title")
    
    static let navigationTitleIntro             = NSLocalizedString("Intro", comment: "Intro screen navigation title")
    static let buttonTitleBegin                 = NSLocalizedString("Begin journey", comment: "Begin journey button title")
    static let messageFailedLoadGame            = NSLocalizedString("Failed to load game", comment: "Error message when failed to load game")

    static let messageFormatDirection           = NSLocalizedString("Direction %@ to %d", comment: "Direction title format")
    
    static let longSword                        = NSLocalizedString("Long sword", comment: "Long sword name")
    static let leatherArmor                     = NSLocalizedString("Leather Armor", comment: "Leather armor name")
    static let lamp                             = NSLocalizedString("Lamp", comment: "lamp name")
    static let player                           = NSLocalizedString("Player", comment: "Player title")
    
    static let eventDescriptionAdvance          = NSLocalizedString("Advanced to scene %d", comment: "Advance event description format")
    static let eventDescriptionGain             = NSLocalizedString("Gained %d %@ bonus", comment: "Bonus event description format")
    static let eventDescriptionDamageTaken      = NSLocalizedString("Damage taken: %d", comment: "Damage event description format")
    static let eventDescriptionDrinkPotion      = NSLocalizedString("Drank potion of %@", comment: "Drink event description format")
    static let eventDescriptionEat              = NSLocalizedString("Ate a portion of food, gained %d health", comment: "Eat event description")
    static let eventDescriptionEscape           = NSLocalizedString("Lost %d health while escaping fight", comment: "Escape event description format")
    static let eventDescriptionFigtRound        = NSLocalizedString("Fight round with %@, attack: %d, opponent attack: %d", comment: "Fight event description format")
    static let eventDescriptionKill             = NSLocalizedString("Killed %@", comment: "Kill event description format")
    static let eventDescriptionRest             = NSLocalizedString("Rest gained %d health and %d dexterity", comment: "Rest event description format")
    static let eventDescriptionRoll             = NSLocalizedString("Rolled %d", comment: "Roll event description format")
    static let eventDescriptionTryLuck          = NSLocalizedString("Tryed luck. Rolled %d = %@", comment: "Try luck event description format")
    static let eventDescriptionDied             = NSLocalizedString("Died", comment: "Die event description")
    static let eventDescriptionUseItem          = NSLocalizedString("Used %d amount of %@", comment: "Use invetory item event description format")
    static let eventDescriptionDamageMod        = NSLocalizedString("Damage modified from %d to %d due %@", comment: "Damage modification event description format")
    static let eventDescriptionAddInventory     = NSLocalizedString("Added %@ to inventory", comment: "Add inventory item event description format")
    static let eventDescriptionDroppedAmount    = NSLocalizedString("Dropped %d of %@", comment: "Drop inventory item event description format with amount")
    static let eventDescriptionDropItem         = NSLocalizedString("Dropped %@", comment: "Drop inventory item event description format")
    static let eventDescriptionAttackMod        = NSLocalizedString("Attack modified by %d", comment: "Attack modified event description format")
    static let eventDescriptionQueryAnswer      = NSLocalizedString("%@ answered %@ for %@", comment: "Query action answer format")
    static let correctly                        = NSLocalizedString("Correctly", comment: "Correct answer")
    static let wrongly                          = NSLocalizedString("Wrongly", comment: "Wrong answer")
    static let eventDescriptionExtraDamageTaken = NSLocalizedString("Extra attack damage taken: %d", comment: "Extra attack damage without caption format")
    static let eventDescriptionExtraDamageCause = NSLocalizedString("Extra attack damage taken: %d due %@", comment: "Extra attack damage with caption format")
    static let eventDescriptionExtraDamageAvoid = NSLocalizedString("Extra attack avoided with luck", comment: "Extra attack avoided event description")
    static let eventDescriptionExtraAttackOpp   = NSLocalizedString("Extra attack from opponent: %@", comment: "Extra attack from opponent event description")
    static let eventDescriptionExtraAttackAvoid = NSLocalizedString("Extra attack avoided with luck", comment: "Extra attack avoided event description")
    
    static let itemDescriptionFormatPotion      = NSLocalizedString("Potion of %@ (rations: %d)", comment: "Potion name format")
    static let itemDescriptionFood              = NSLocalizedString("Food", comment: "Food title")
    static let itemDescriptionFormatFood        = NSLocalizedString("Food (rations: %d)", comment: "Food description format")
    static let itemDescriptionFormatMoney       = NSLocalizedString("Coins (%d)", comment: "Money description format")
    static let itemDescriptionWeapon            = NSLocalizedString("Weapon", comment: "Weapon title")
    static let itemDescriptionSword             = NSLocalizedString("Sword", comment: "Sword title")
    static let itemDescriptionArmor             = NSLocalizedString("Armor", comment: "Armor title")
    static let itemDescriptionShield            = NSLocalizedString("Shield", comment: "Shield title")
    static let itemDescriptionHelmet            = NSLocalizedString("Helmet", comment: "Helmet title")
    static let itemDescriptionGloves            = NSLocalizedString("Gloves", comment: "Gloves title")
    
    static let actionDescriptionTryLuck         = NSLocalizedString("Try your luck!", comment: "Try luck action default caption")
    static let actionDescriptionFight           = NSLocalizedString("Fight!", comment: "Fight action default caption")
    static let actionDescriptionRest            = NSLocalizedString("Get some rest!", comment: "Rest action default caption")
    static let actionDescriptionRoll            = NSLocalizedString("Roll!", comment: "Roll action default caption")
    static let actionDescriptionEscape          = NSLocalizedString("Escape!", comment: "Escape action default caption")
    static let actionDescriptionForce           = NSLocalizedString("Force!", comment: "Force action default caption")
    static let actionDescriptionGamble          = NSLocalizedString("Gamble!", comment: "Gamble action default caption")
    static let actionDescriptionQuery           = NSLocalizedString("You have to answer a question", comment: "Query action default caption")
    static let actionDescriptionTrade           = NSLocalizedString("Pst! Would you like to buy sumething?", comment: "Trade action default caption")
    static let opponent                         = NSLocalizedString("Opponent", comment: "Opponent default title")
    
    static let messageFormatRolled              = NSLocalizedString("You rolled %d", comment: "Roll value format")
    
    static let directionNorth                   = NSLocalizedString("north", comment: "Direction North")
    static let directionSouth                   = NSLocalizedString("south", comment: "Direction South")
    static let directionEast                    = NSLocalizedString("east", comment: "Direction Est")
    static let directionWest                    = NSLocalizedString("west", comment: "Direction West")
    static let directionBack                    = NSLocalizedString("back", comment: "Direction Back")
    static let unknown                          = NSLocalizedString("unknown", comment: "Unknown title")
}
